name: release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements-build.txt

      - name: Build binary
        run: pyinstaller main.spec

      - name: Create tarball
        run: |
          mv dist/ rocm-smi-exporter/
          tar -czf rocm-smi-exporter-${{ github.ref_name }}.tar.gz rocm-smi-exporter/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: rocm-smi-exporter-${{ github.ref_name }}.tar.gz
